apiVersion: v1
kind: Service
metadata:
  labels:
    system: server2
  name: server2
spec:
  ports:
  - name: fl-port
    port: 8102
    protocol: TCP
    targetPort: 8102
  - name: admin-port
    port: 8103
    protocol: TCP
    targetPort: 8103
  selector:
    system: server2
