apiVersion: v1
kind: Service
metadata:
  labels:
    system: server1
  name: server1
spec:
  ports:
  - name: fl-port
    port: 8002
    protocol: TCP
    targetPort: 8002
  - name: admin-port
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    system: server1
